name: Receive Key Publicly

on:
  workflow_dispatch:
    inputs:
      key:
        description: "Key từ HTML"
        required: true
        type: string

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\":\"update_key\",\"client_payload\":{\"key\":\"${{ github.event.inputs.key }}\"}}"
